projects:
  essentialism:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src\graphql
        graphQLApiId: knjqkklasjadbayfj6dzphp7ae
      endpoints:
        prod: >-
          https://bmlwgzfulna4ffm5qhpvlt3yzm.appsync-api.us-east-1.amazonaws.com/graphql
